[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Redirect API routes for clean paths if desired
[[redirects]]
  from = "/api/openai-titles"
  to = "/.netlify/functions/openai-titles"
  status = 200

[[redirects]]
  from = "/api/stripe-checkout"
  to = "/.netlify/functions/stripe-checkout"
  status = 200


